[package]
name = "pbr_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
bevy_tasks = "0.19.1"
bitvec = "1.1.1"
bytemuck = "1.25.1"
egui = { version = "0.35.0", features = ["persistence"] }
egui-wgpu = { version = "0.35.0" }
egui-winit = { version = "0.35.0" }
fastnoise2 = "0.4.0"
glam = { version = "0.33.2", features = ["bytemuck"] }
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
pollster = "1.0.1"
static_assertions = "1.1.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "ansi"] }
wesl = "0.4.1"
wgpu = "29.0.4"
wgpu-profiler = { version = "0.27.0", features = ["tracy"] }
winit = "0.30.13"

[build-dependencies]
wesl = "0.4.1"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
