[package]
name = "pbr_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
bitvec = "1.1.1"
bytemuck = "1.25.1"
egui = { version = "0.35.0", features = ["persistence"] }
egui-wgpu = { version = "0.35.0" }
egui-winit = { version = "0.35.0" }
glam = { version = "0.33.2", features = ["bytemuck"] }
pollster = "1.0.1"
slab = "0.4.12"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
wesl = "0.4.1"
wgpu = "29.0.4"
wgpu-profiler = "0.27.0"
winit = "0.30.13"

[build-dependencies]
wesl = "0.4.1"
